# Generated by Django 5.0.14 on 2026-07-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
