# Generated by Django 5.0.14 on 2026-07-21 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_sellerprofile_total_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
